#define NO_TWITCH_SUB ""
#define TWITCH_SUB_TIER_1 "1000"
#define TWITCH_SUB_TIER_2 "2000"
#define TWITCH_SUB_TIER_3 "3000"

#define ACCESS_TWITCH_UNSUBBED 0
#define ACCESS_TWITCH_SUB_TIER_1 1
#define ACCESS_TWITCH_SUB_TIER_2 2
#define ACCESS_TWITCH_SUB_TIER_3 3
